### PR TITLE
add midi output

### PR DESCRIPTION
**Pull request by Maarten-buelens**
I didn't like the latency when using audio from the PC.
For example when playing with only 1 hand.

So this allow you to play all audio from the piano itself.

There isn't yet a settings entry for this.

### CODE REVIEW

**Comment by Maarten-buelens** [comment]
I refactored some names.
moved all `midi.press_output()` to instrument synth
and added the ability to mute piano output using mastervolume

There should maybe be a different volume mute for midi output but I am not very experienced in react or typescript.

**Comment by samouri** [comment]
Hey @Maarten-buelens!

I just tested out this branch and it was fantastic hearing the music come out of the piano instead of my tinny laptop speakers 🎉 . Code looks good too.

There are a two updates I think it needs before it's ready for merge:

1. The [MIDIModal](https://github.com/sightread/sightread/blob/main/src/features/pages/PlaySong/components/MidiModal.tsx#L13) should have an "Inputs" and "Outputs" section instead of just an "Available devices" one. The device running sightread should be considered one of the devices too, so you could disable the laptop/tablet etc.

Fur Elise - MIDI

2. (lower priority) The master volume slider should also modify the output volume in the midi out, instead of only checking for != 0

---

Once those two are solved I think this is good to do!
Let me know if you'd like to try to make those changes

**Comment by Maarten-buelens** [comment]
Sure i will try to add those.

**Comment by Maarten-buelens** [comment]
added first feature

afbeelding

**Comment by Maarten-buelens** [comment]
And that was the volume control for the midi output.

I think it is finished, so if you could take a look at it that would be great.

**Comment by samouri** [comment]
@Maarten-buelens, I'll review, tweak, and deploy the updates this weekend

**Comment by samouri** [comment]
@Maarten-buelens: I couldn't figure out how to push some small changes directly to this PR (which I think would involve pushing to your fork). So instead I merged it to the `add-midi-output` branch, and then staged changes onto that (https://github.com/sightread/sightread/pull/134).

Thank you for the pull request and the updates!  It worked very well :)

**Pull request merged**
