### PR TITLE
Adding Volume input range

### PR DESCRIPTION
**Pull request by samouri**
**summary**
Iterates on https://github.com/sightread/sightread/pull/82
Closes https://github.com/sightread/sightread/issues/72

Screen Shot 2023-03-09 at 11 22 32 AM

### CODE REVIEW

**Comment by samouri** [comment]
Update on [my previous comment](https://github.com/sightread/sightread/pull/82#pullrequestreview-1186413265) related to clicking the volume button toggling volume.

After implementing it that way, I realized it only makes sense UX wise if the volume slider is always visible. If only visible based on hover, then modifying volume becomes frustratingly difficult w/ precision mouse movements required.

I reverted to clicking only for hiding and showing the volume slider

**Comment by emmaoberstein** [comment]
Screenshot 2023-03-09 at 11 57 19 AM

The icon doesn't look centered compared to the rest of icons

**Comment by emmaoberstein** [comment]
Should we use cursor: pointer for the slider?

**Comment by emmaoberstein** [comment]
Suggested behavior, copying youtube: clicking on volume toggles on/off. Hovering over volume opens the slider, which stays open until hover away

**Pull request merged**
